[package]
name = "datastruct_derive"
version = "0.0.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
quote = "1"
proc-macro2 = "1.0"
syn = { version = "1.0", features = ["full", "printing"] }
itertools = "0.12.1"

